- pyvlx/interface.py
- pyvlx/pyvlx.py
- test.py
I just recognized that I’m not able to login to the KLF 200 webinterface at all after using the wrapper, because the KLF 200 allows only one logged in user at a time. I’m not a python developer at all, but added some lines to logout which only works if you call the disconnect method separately. I don’t know if this is best practice, but feels better than logging out automatically after each and every other call. So, for me it works. I call disconnect at the end of my script that uses the wrapper and am directly allowed to login to the webinterface to do some changes.
> added disconnect

- pyvlx/devices.py
Enable management of dual shutters. It is to be noted that dual shutters are not properly managed in Velux API v1, ie it is not possible to close the lower shutter without the upper one to be closed.
> Enable management of dual shutters

- examples/example.py
- pyvlx/interface.py
- pyvlx/pyvlx.py
klf200 is responding after a request is fully handled again (e.g. running a scene is completed). Thus, a following request run into timeout, which needs to be made adjustable to users environment (e.g. a blind is running longer than a roller shutter)
> timeout of api calls configurable

- pyvlx/__init__.py
- pyvlx/node_helper.py
- pyvlx/opening_device.py
I have a gate drive from Somfy (Ixengo L 3S IO). Unfortunately, I cannot control this gate directly with Home Assistant, so an integration of the gate control is needed. My Somfy gate has the node type GATE_OPENER_ANGULAR_POSITION, so I added both types (GATE_OPENER and GATE_OPENER_ANGULAR_POSITION).
> Added support for Gate type.

- pyvlx/frames/frame_get_node_information.py
- pyvlx/lightening_device.py
- pyvlx/node.py
- pyvlx/node_helper.py
- pyvlx/on_off_switch.py
- pyvlx/opening_device.py
- test/lightening_device_test.py
- test/node_helper_test.py
- test/nodes_test.py
- test/opening_device_test.py
Home Assistant wants entities to provide a unique id. Neither the host ip nor the node_id are unique. The PR adds the serial number during node initialization.
If the PR is accepted and pypi version containing the PR is available, I will update https://github.com/home-assistant/core/pull/34668
Regards, Thomas
> Make nodes aware of their serial_number.

- pyvlx/__init__.py
- pyvlx/node_helper.py
- pyvlx/opening_device.py
- test/nodes_test.py
- test/opening_device_test.py
This will allows to access the correct position states of opening devices directly after node creation.
> Set initial position of OpeningDevice during node construction.

- Makefile
- examples/monitor.py
- pyvlx/__init__.py
- pyvlx/frames/frame_get_all_nodes_information.py
- pyvlx/frames/frame_get_node_information.py
- pyvlx/node_updater.py
- test/frame_get_all_nodes_information_ntf_test.py
- test/frame_get_node_information_ntf_test.py
- test/node_helper_test.py
Background
------------
Looks like some devices don't report Serial numbers. This should be handled within HASS correctly.
@tschamm @pawlizio : Just an idea, what do you think?
> Handle devices without serial numbers.

- pyvlx/api/frame_creation.py
> Access enum from the Enum class instead of instance which is deprecated since Python 3.10.

- .travis.yml
- pyvlx/api/frames/frame_error_notification.py
- pyvlx/api/frames/frame_get_all_nodes_information.py
- pyvlx/api/frames/frame_get_node_information.py
- tox.ini
Also a minor travis.yml item and a tox warning fix
> Pylint fixes

- pyvlx/heartbeat.py
Hi!
I have noticed that the heartbeats seem to stop after a KLF reboot (or any other reconnect).
After looking into the code it seems like the heartbeat is not recreated, so after the stop function was called once, the stopped parameter stays False and will never be set back to True. Therefore when start is called at the next reconnect (at least it seems like it is called) it will immediately stop again.
This PR has fixed the issue for me, but i did not dig deeper into the code and did not do rigorous testing.
As a side effect this seems to have fixed some issues with the HouseStatusmonitor (states were not being updated)
> reset heartbeat on .start()

- pyvlx/heartbeat.py
self.stopped_event is never cleared, so it should cause problems on the second stop of heartbeat.
> Clear Heartbeat stopped_event

- pyvlx/parameter.py
- test/position_test.py
This PR fixes a problem I am having with Somfy Venetian Blinds.
They seem to send values that are not expected in pyvlx.
My solution is to not throw an exception during parsing but rather return UNKNOWN_VALUE. Throwing the exception caused the connection to be terminated. Which caused considerable lags when changing a value in HA because pyvlx had to first reconnect. At some point the gateway seems to get stuck and has to be unplugged, too.
Example exception from HA log:
```
pyvlx.exception.PyVLXException: <PyVLXException description="parameter::raw_exceed_limit" raw="b'\xfe\x01'"/>
pyvlx.exception.PyVLXException: <PyVLXException description="parameter::raw_exceed_limit" raw="b'\xd8\x00'"/>
```
> Convert unknown values to Position.UNKNOWN_VALUE rather than throwing an exception

- pyvlx/opening_device.py
This solves #123
I've prepared and tested a configuration posibility via HA. For open_orientation and close_orientation I've created NumberEntities which can be adjusted by a slider in HA between a range of 0 and 100. So you can define your desired open and close orientation which will be used if you press the arrow buttons. You can try this also using my custom compent, but you have to use the branch "add_orientation_config": https://github.com/pawlizio/my_velux/tree/add_orientation_config
It looks as follows:
> Add Configuration options for open/close orientation

- pyvlx/pyvlx.py
This PR moves the start of the heartbeat to the connect method to solve the failed tests of the Home Assistant integration. 
https://github.com/home-assistant/core/pull/89155
> Move heartbeat start from init to connect method

- pyvlx/api/api_event.py
- pyvlx/api/get_all_nodes_information.py
- pyvlx/pyvlx.py
Fixes #331. I've tested this a few times with a set of 6 blinds, and if I do `node.close()` for all of them in parallel without this, I get roughly half closing (sometimes 2, sometimes 4-5). With this change they appear pretty stable all 6 happening. They don't quite run all at the same time, there's a bit of a gap between them (1s maybe?), but that's a lot better than them not closing.
> Uses a Semaphore to limit API calls to one at a time to avoid KLF issues

- pyvlx/opening_device.py
- pyvlx/parameter.py
> Fix for #355

- pyvlx/opening_device.py
We should initiate with TargetPosition, otherwise Blind orientation can not be changed until position has been changed on HA start.
> Fix blind orientation on first call

- setup.py
Otherwise:
```
* Messages for package dev-python/pyvlx-0.2.21:
* The following unexpected files/directories were found top-level
* in the site-packages directory:
*
*   /usr/lib/python3.11/site-packages/test
*
* This is most likely a bug in the build system.  More information
* can be found in the Python Guide:
* https://projects.gentoo.org/python/guide/qawarn.html#stray-top-level-files-in-site-packages
* ERROR: dev-python/pyvlx-0.2.21::HomeAssistantRepository failed (install phase):
*   Failing install because of stray top-level files in site-packages
```
I hope you don't mind I included your component for [Home Assistant Gentoo Overlay](https://github.com/onkelbeh/HomeAssistantRepository). I do not use this component myself. But, during compilation test, the installation test script …
> Update setup.py, exclude 'test'

- .github/workflows/ci.yml
- pyvlx/__init__.py
- pyvlx/discovery.py
- pyvlx/pyvlx.py
- requirements/production.txt
- setup.py
Add zeroconf discovery support for Velux KLF200 devices on the network.
> Add zeroconf discovery support

- pyvlx/pyvlx.py
- setup.py
I think we should include the reboot function directly into KLF200 disconnect command. I know the KLF200 open it's WIFI Access Point on restart, however you need to have the creditentials to connect to this AP, so I think this solution can be justified as workaround.
This PR is a workaround to avoid #53, #68 and #30
> Reboot KLF200 on disconnect

- .github/workflows/ci.yml
- pyvlx/connection.py
- test/frame_get_local_time_cfm_test.py
See: https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_default_certs
> Fix blocking calls on ssl_context

- pyvlx/opening_device.py
Setting actual position from set_possition_command cannot be used, as target_position values can be out of range, in example if stop commands are submitted. Instead we should wait for the KLF200 to report the actual position.
This PR has been tested and it solves: https://github.com/pawlizio/my_velux/issues/69
> Dont set actual position from command

- pyvlx/parameter.py
- test/position_test.py
The library already has code for some covers that report values only close to 0xC800 when at 100%, but the code for reporting a status == closed broke with commit https://github.com/Julius2342/pyvlx/commit/46992b4637d1163157d76e7ca2bb377882124f55
This PR fixes the regression and adds tests for it.
> fix recognition of status closed 
